sonar.projectKey=devops-final
sonar.projectName=DevOps Final - User Management
sonar.projectVersion=1.0
sonar.organization=luongthaydoi07

# Source & Tests
sonar.sources=frontend/src,backend/app
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/test_*.py
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**,**/venv/**,**/migrations/**

# JavaScript / React coverage
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Python coverage
sonar.python.version=3.11
sonar.python.coverage.reportPaths=backend/coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8
